#!/bin/bash
set -u

# supportconfig plugin for hanadb_exporter
#
# v1.0
#
# February 2024    v1.0    first release

SVER='1.0.0'
TITLE="SUSE supportconfig plugin for hanadb_exporter"

function display_package_info() {
    echo -e "\n#==[ Command ]======================================#"
    echo -e "# rpm -qi ${1}"
    rpm -qi "${1}"

    echo -e "\n#==[ Command ]======================================#"
    echo -e "# rpm -V ${1}"
    rpm -V "${1}"
}

function display_file_stat() {
    echo -e "\n#==[ File ]===========================#"
    echo -e "# ls -ld ${1} ; stat ${1} \n"

    if [ -e "${1}" ] ; then
        ls -ld "${1}"
        echo
        stat "${1}"
    else
        echo "${1} does not exist!"
    fi
}

function display_file() {
    echo -e "\n#==[ File Content ]===========================#"
    echo -e "# cat ${1}"

    if [ -e "${1}" ] ; then
        cat "${1}"
    else
        echo "${1} does not exist!"
    fi
}

function display_systemd_status() {
    echo -e "\n#==[ Command ]======================================#"
    echo -e "# systemctl status ${1}"

    systemctl status ''"${1}"'' 2>&1
}

function display_cmd() {
    ORG_CMDLINE="${@}"
    CMDBIN=${ORG_CMDLINE%% *}
    FULLCMD=$(\which $CMDBIN 2>/dev/null | awk '{print $1}')
    echo -e "\n#==[ Command ]======================================#"
    if [ -x "$FULLCMD" ]; then
        CMDLINE=$(echo $ORG_CMDLINE | sed -e "s!${CMDBIN}!${FULLCMD}!")
        echo -e "# $CMDLINE"
        echo "$CMDLINE" | bash
    else
        echo -e "# $ORG_CMDLINE"
        echo "Command not found or not executable"
    fi
}

function display_log() {
    local file
    echo -e "\n#==[ Log Files ]====================================#"
    for file in "${@}" ; do
        echo -e "\n# ${file}"
        SKIP_FILE=$(echo ${file} | egrep "tbz$|bz2$|gz$|zip$")
        if [ -n "$SKIP_FILE" ]; then
            echo -e "skipping..."
            continue
        fi
        cat "${file}"
        echo -e "######"
    done
}

# ---- Main ----
echo -e "Supportconfig Plugin for $TITLE, v${SVER}"

display_package_info prometheus-hanadb_exporter
# use 'pattern' for systemctl status cmd
display_systemd_status "*hanadb_exporter*"

for file in /usr/etc/hanadb_exporter/* /etc/hanadb_exporter/*; do
    [ -e "${file}" ] && { display_file_stat "${file}" ; display_file "${file}" ; echo ; }
done

# default log file
display_log /var/log/hanadb_exporter*
# get logfile name from config file
if [ -f /etc/hanadb_exporter/config.json ]; then
    logfile_from_config=$(sed -n 's%[[:blank:]]*"log_file":[[:blank:]]*"\(.*\)"%\1%p' /etc/hanadb_exporter/config.json)
    [[ "$logfile_from_config" != "/var/log/hanadb_exporter.log" ]] && [ -f "$logfile_from_config" ] && display_log $logfile_from_config
fi
# log entries from syslog
display_cmd "grep -E -i 'hanadb_exporter\[.*\]:' /var/log/messages"

display_cmd "ss -tulpan | grep exporter"

# Bye.
exit 0
