{
 "title": "SAP HANA",
 "description": "Shows detailed stats of a SAP HANA database. Brought to you by SUSE.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node_name",
    "label": "Node",
    "query": "label_values(hanadb_host_memory_used_total_mb, host)"
   },
   {
    "name": "node_ip",
    "query": "label_values(node_uname_info{nodename=\"$node_name\"}, instance)"
   },
   {
    "name": "sid",
    "label": "SID",
    "query": "label_values(hanadb_host_memory_used_total_mb{host=\"$node_name\"}, sid)"
   },
   {
    "name": "instance_number",
    "label": "Instance number",
    "query": "label_values(hanadb_host_memory_used_total_mb{host=\"$node_name\", sid=\"$sid\"}, insnr)"
   },
   {
    "name": "database_name",
    "label": "Database",
    "query": "label_values(hanadb_host_memory_used_total_mb{host=\"$node_name\", sid=\"$sid\", insnr=\"$instance_number\"}, database_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_host_memory_physical_free_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Free Physical Memory"
    },
    {
     "expr": "hanadb_host_memory_resident_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Resident Memory "
    },
    {
     "expr": "hanadb_host_memory_pool_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "hanadb_host_memory_used_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Used"
    },
    {
     "expr": "hanadb_host_memory_swap_used_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Swap"
    },
    {
     "expr": "hanadb_host_memory_code_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Code size"
    },
    {
     "expr": "hanadb_host_memory_shared_alloc_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Shared"
    },
    {
     "expr": "hanadb_column_tables_used_memory_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / 1024",
     "legendFormat": "Column Store Tables"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "description": "Percentage of Total Used RAM over the HANA Allocation Limit.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hanadb_host_memory_used_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) / sum(hanadb_host_memory_alloc_limit_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Average percent of CPU usage based on usage type.",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(hanadb_cpu_system_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})",
     "legendFormat": "% System Time"
    },
    {
     "expr": "avg(hanadb_cpu_user_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})",
     "legendFormat": "% User Time"
    },
    {
     "expr": "avg(hanadb_cpu_waitio_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})",
     "legendFormat": "% Wait I/O"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Average CPU busy time of all cores.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(hanadb_cpu_busy_percent{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(hanadb_alerts_current_rating{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_connections_total_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{connection_type}} : {{connection_status}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "description": "Details HANA on how HANA uses the filesystem in its various directories",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(hanadb_disk_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / hanadb_disk_total_device_size_mb)",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "File system details",
   "type": "table-old",
   "description": "Details HANA on how HANA uses the filesystem in its various directories",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "hanadb_disk_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\",usage_type!=\"ROOTKEY_BACKUP\"} + 0",
     "legendFormat": "Usage by type"
    },
    {
     "expr": "hanadb_disk_total_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\",usage_type!=\"ROOTKEY_BACKUP\"} + 0",
     "legendFormat": "Disk Total Size"
    },
    {
     "expr": "(hanadb_disk_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\",usage_type!=\"ROOTKEY_BACKUP\"} / hanadb_disk_total_size_mb) * 100",
     "legendFormat": "Percent Used by type"
    },
    {
     "expr": "hanadb_disk_total_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\",usage_type!=\"ROOTKEY_BACKUP\"} + 0",
     "legendFormat": "Total Device Usage"
    },
    {
     "expr": "(hanadb_disk_total_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\",usage_type!=\"ROOTKEY_BACKUP\"} / hanadb_disk_total_size_mb) * 100",
     "legendFormat": "Device Percent Used"
    },
    {
     "expr": "hanadb_disk_total_device_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\",usage_type!=\"ROOTKEY_BACKUP\"}",
     "legendFormat": "Total Device Size"
    }
   ]
  },
  { "title": "Internal alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Alert counts by rating",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(hanadb_alerts_current_rating{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} == 1) or vector(0)",
     "legendFormat": "Info"
    },
    {
     "expr": "count(hanadb_alerts_current_rating{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} == 2) or vector(0)",
     "legendFormat": "Low"
    },
    {
     "expr": "count(hanadb_alerts_current_rating{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} == 3) or vector(0)",
     "legendFormat": "Medium"
    },
    {
     "expr": "count(hanadb_alerts_current_rating{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} == 4) or vector(0)",
     "legendFormat": "High"
    },
    {
     "expr": "count(hanadb_alerts_current_rating{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} == 5) or vector(0)",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Alert details",
   "type": "table-old",
   "description": "Alerts raised from the HANA database internal alerting system",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 27 },
   "targets": [
    {
     "expr": "sort_desc(hanadb_alerts_current_rating{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) "
    }
   ]
  },
  { "title": "Detailed stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory usage by service",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_memory_service_total_used_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "SQL Executions Statistics",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_service_executions_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0)"
    },
    {
     "expr": "hanadb_sql_service_elapsed_time_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_elap_per_exec_avg_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_lock_per_exec_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sql_service_max_ela_time_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  {
   "title": "Top SQL Time Consumers",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_top_time_consumers_mu{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0)"
    },
    {
     "expr": "hanadb_sql_top_time_consumers_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  {
   "title": "Used Memory by Schema",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sort(sum(hanadb_schema_used_memory_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) by (schema_name))",
     "legendFormat": "{{schema_name}}"
    }
   ]
  },
  {
   "title": "Top SQL Memory Consumers",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sort(hanadb_sql_top_mem_consumers_byte{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0)"
    },
    {
     "expr": "sort(hanadb_sql_top_mem_consumers_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0)"
    }
   ]
  },
  {
   "title": "TOP CS Tables Memory Consumers",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sort(hanadb_table_cs_top_mem_total_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_estimated_max_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_disk_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_table_cs_top_mem_record_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  {
   "title": "DATA Files Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "hanadb_disk_data_files_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_disk_data_files_total_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "(hanadb_disk_data_files_used_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} / hanadb_disk_data_files_total_size_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}) * 100"
    }
   ]
  },
  { "title": "System Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "HANA System Replication Status",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "hanadb_sr_replication_status{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_secondary_active_status{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_secondary_reconnect_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_secondary_failover_count{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  {
   "title": "System Replication Log Shipping Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hanadb_sr_ship_delay_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{host}}:{{port}} -> {{secondary_host}}:{{secondary_port}}"
    }
   ]
  },
  {
   "title": "System Replication Used Async Log Shipping Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "hanadb_sr_async_used_shipping_buffer_mb{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{host}}:{{port}} -> {{secondary_host}}:{{secondary_port}}"
    }
   ]
  },
  {
   "title": "System Replication Takeover History",
   "type": "table-old",
   "description": "System Replication Takeover history. When the values of end time cannot be collected, the duration time is presented as -1 and the end time as \"N/A\"",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "hanadb_sr_takeover_replication_status{src_host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_takeover_duration_time_seconds{src_host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_takeover_log_position_bigint{src_host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    },
    {
     "expr": "hanadb_sr_takeover_shipped_log_position_bigint{src_host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"} + 0"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Receive Rate (KB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_receive_rate_kb_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Transmission Rate (KB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_transmission_rate_kb_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Receive/Transmission Errors per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_receive_rate_errors_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}} - Rec. rate"
    },
    {
     "expr": "hanadb_network_transmission_rate_errors_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}} - Trans. rate"
    }
   ]
  },
  {
   "title": "Received Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_receive_requests_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Transmitted Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_transmission_rate_requests_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Collisions per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hanadb_network_collisions_per_seconds{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "I/O Throughput",
   "type": "graph",
   "description": "I/O Throughput  per Disk in KB/Sec",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_throughput_kb_second{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "I/O Latency in miliseconds.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_latency_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "I/O Service Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 109 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_service_time_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Requests per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_requests_per_second{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Queue Length (Number of Requests)",
   "type": "graph",
   "description": "average queue length of the requests that were issued to the Disk Device",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_queue_length_requests{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "I/O Wait Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 118 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hanadb_disk_io_wait_time_ms{host=~\"$node_name\",sid=~\"$sid\",insnr=~\"$instance_number\",database_name=~\"$database_name\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}